### ISSUE TITLE
Add license to site

### ISSUE THREAD

**Issue by frogcrush** [trucsclub/trucsclub.github.io#104]
No license is included with the source files for this site. We should add one.

**Comment by marcolussetti** [comment]
I actually would say we should keep it copyrighted as it.

**Comment by mitchhentges** [comment]
I agree with Marco, the site doesn't necessarily make sense to be open. Besides, it wouldn't even be beneficial to the community to be able to reuse our code.
Hunting down previous contributors would be a hassle, too

**Comment by frogcrush** [comment]
Were there contributers before the project was added to Github? If not, I only see two people outside the current board who have commited any code.

Not having a license implies that even board members cannot use, modify or share the code for any purpose. The only reason we can view and fork the code is because of the Github TOS.

It also implies that we don't embrace the open source community ;)

**Comment by mitchhentges** [comment]
If there's no explicit license, doesn't that just mean the the organization is the only entity that owns and is allowed to modify/shared/etc the code? And since board members are part of the organization, we're authorized?
