### ISSUE TITLE
Add board meetings

### ISSUE THREAD

**Issue by marcolussetti** [trucsclub/trucsclub.github.io#105]
We should add location and time of our board meeting so that interested third parties can attend.

**Comment by frogcrush** [comment]
Where would you want to add it? (What page?)

**Comment by mitchhentges** [comment]
It should be on the "About" page, within "Get Involved"

**Comment by LavenderGoons** [comment]
Should I just put they happen 8:30 at IB 1010

**Comment by mitchhentges** [comment]
Make a small sub-section under "Get Involved", called "Board Meetings". Say that run run every week at 8:30pm on Tuesday in IB 1010.
