### ISSUE TITLE
Elections page says board members are limited

### ISSUE THREAD

**Issue by frogcrush** [trucsclub/trucsclub.github.io#198]
> The TRU Computer Science Club board is a group of 10 members that run the club's day-to-day operations, organize events, manage the support lab, and work with the TRU faculty.

This is no longer correct.

**Comment by superg2009** [comment]
i would suggest maybe removing "of 10 members" but this is open to debate on the exact wording

**Comment by frogcrush** [comment]
That's exactly what I think.
