### ISSUE TITLE
No Updates are visible on home page

### ISSUE THREAD

**Issue by frogcrush** [trucsclub/trucsclub.github.io#200]
![image](https://user-images.githubusercontent.com/6116333/77378332-ee2de900-6d32-11ea-9207-410f3cd916b6.png)

**Comment by superg2009** [comment]
weird, loads for me on my machine but i did notice a dev message in devtools:
"You may have been affected by an update to settings in embedded timelines. See https://twittercommunity.com/t/deprecating-widget-settings/102295. "

**Comment by frogcrush** [comment]
Oof, hit by something deprecated in 2018? Brutal.

**Comment by superg2009** [comment]
`<a class="twitter-timeline" href="https://twitter.com/TRUCSClub?ref_src=twsrc%5Etfw">Tweets by TRUCSClub</a> <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script> `
this would be the appropriate html and JS minus any extra attributes we may have added
