### ISSUE TITLE
Add information about Weekly Game Night

### ISSUE THREAD

**Issue by frogcrush** [trucsclub/trucsclub.github.io#204]

**Comment by superg2009** [comment]
@frogcrush should we put this on events.html ?

**Comment by frogcrush** [comment]
Maybe, but I'm leaning towards thinking it needs its own page

**Comment by superg2009** [comment]
this in progress

**Comment by frogcrush** [comment]
@superg2009 any update?

**Comment by superg2009** [comment]
this is done for now with the events blurb. ideally more work to be done
