### ISSUE TITLE
Add "Free stuff" page

### ISSUE THREAD

**Issue by frogcrush** [trucsclub/trucsclub.github.io#206]
We should create a page that links to free stuff for students such as:

- Microsoft Imagine/DreamSpark/Azure Education/whatever they call it next month (and outline what we get eg Windows, VS Enterprise, etc)
- JetBrains stuff
- GitHub Education Pack
- Microsoft Office

We could also outline deals if we wanted:
- Spotify
- Amazon Prime
etc

**Comment by superg2009** [comment]
Also

- LinkedIn Learning (i guess...)

- https://www.axure.com/edu

- I think Tableau has one

**Comment by frogcrush** [comment]
Also for Azure/Imagine/whatever, we should have some instructions on how to sign up and access it because it's kinda convoluted and shitty. And I've had to walk a few people through the process.

**Comment by frogcrush** [comment]
- Autodesk
- Syncfusion
