### ISSUE TITLE
Add "Super Secret TRU Resources" page (page of stuff they don't make known very well)

### ISSUE THREAD

**Issue by frogcrush** [trucsclub/trucsclub.github.io#211]
For example:
- Can live chat librarians (https://www.tru.ca/library.html > Live Chat)
- Access to a lot of stuff like IEEE Explore, etc
- If you're on student loans and go on co-op, you have to fill out paperwork or NSLSC ***** you

More? I know there is some crazy stuff I've learned and haven't had a good place to share, but I can't think of any more right now.

**Comment by frogcrush** [comment]
Degree Planner is something I just found out about inside of MyTRU. How are we not told about it???? WHY DID BUSINESS ADVISING HAVE TO TELL ME ABOUT IT

**Comment by superg2009** [comment]
LMFAO, I just say it as an option one day
