### ISSUE TITLE
Deployment

### ISSUE THREAD

**Issue by chrisfosterelli** [trucsclub/trucsclub.github.io#23]
I'd love to get this site out the door.
Does anyone object to starting to move forward with releasing this?

Is there anything else we need before this ships?

**Comment by chadfawcett** [comment]
I think it's pretty well ready to at least be launched. Which is good as the web hosting for the current site is about to expire.

**Comment by chrisfosterelli** [comment]
How urgently does it expire?

**Comment by chadfawcett** [comment]
15th. I keep forgetting which server of mine it's on, otherwise I would of given a heads up.

**Comment by chrisfosterelli** [comment]
Ok, no worries. You're the web admin, so if you say its ready then I guess
its ready ;)

I'll give it a day to see if anyone else wants to chime in, then I can
change the DNS over (or you, can't remember who has admin on that).

**Comment by chadfawcett** [comment]
I agree with giving it a day to see if anyone wants to chime in. 

Login should be in Google drive for domain.

**Comment by stevelyall** [comment]
:et's do it!

**Comment by chrisfosterelli** [comment]
Ok, DNS _should_ be propagating now and everything should be good to go soon. Will update when I can confirm. Never done a Github pages deploy before so who knows? :)

**Comment by chrisfosterelli** [comment]
Verified that nothing exploded. DNS should fully propagate in 24-48hrs. Closing this issue, thanks for the hard work getting this out the door everyone, especially @chadfawcett :)
