### ISSUE TITLE
Twitter feed missing from About, Student FAQ, Support Lab pages

### ISSUE THREAD

**Issue by chadfawcett** [trucsclub/trucsclub.github.io#27]
The twitter feed has not been implemented on these pages yet. Should be an easy fix as it just needs to be copy and pasted from the other pages. If no one wants to tackle it, I can get to it later.

**Comment by stevelyall** [comment]
How do we want the feed implemented on these pages? Since it is on the
right hand side of the page on the home page, would it be weird to put it
on the sidebar for those pages?

Maybe we can put a Facebook and Twitter button on the sidebar, with the
twitter feed on the homepage?

**Comment by chadfawcett** [comment]
@stevelyall I like that idea.

I was just thinking more for now as the twitter feed on the right hasn't been merged yet. I guess as soon as that get's merged in it won't matter. I haven't had a chance to look at your new code on #16 yet to see how it works on mobile.

**Comment by stevelyall** [comment]
That's fair enough, it would solve the issue of there being no Facebook
link at all right now too.

No worries, I know we're all busy on other projects!
