### ISSUE TITLE
Thomas is still in list (Mitch is a skrub)

### ISSUE THREAD

**Issue by mitchhentges** [trucsclub/trucsclub.github.io#54]
GG

**Comment by chrisfosterelli** [comment]
I'm assuming you're talking about the "Previous Board Members" list

**Comment by mitchhentges** [comment]
![rekt](https://cloud.githubusercontent.com/assets/7784737/11452652/7dd77834-95a4-11e5-82aa-80ff86731fd6.png)

**Comment by mitchhentges** [comment]
I'm a bigger skrub, Thomas has always been around. I don't know what I was thinking. Putting him back... ?

**Comment by chrisfosterelli** [comment]
Thanks, just be sure to take him out of 'past board members'. This is why
we have that PR review policy ;)
