### ISSUE TITLE
Reorganize "previous board members" to optimize space

### ISSUE THREAD

**Issue by chrisfosterelli** [trucsclub/trucsclub.github.io#73]
The previous board members list is getting suuuuper long. We should maybe move it some place else or make the list more compact.

Thoughts?

**Comment by stevelyall** [comment]
Some options:

* Separate "Past board members" sub-page, not included in main nav but perhaps a link on the current members page 
* Collapsible accordion-type thingy (Bootstrap for the win!) to show or hide past members
* Just remove people and don't keep a list of past members
* Don't keep past board members after a certain amount of time

I'm partial to the first two. @LavenderGoons what do you think?

**Comment by chrisfosterelli** [comment]
@LavenderGoons and I were also discussing that we could save a lot of space by having the list of board members expand into rows that take up the available space. On a desktop that'd be like 3 or 4 rows which would save a lot of space.

I like the idea of collapsing it too.
