### ISSUE TITLE
Implementing site analytics?

### ISSUE THREAD

**Issue by stevelyall** [trucsclub/trucsclub.github.io#75]
It would be interesting to know which parts of the site people visit, and where our referrals come from. It would also be interesting to see how many home page visits actually translate to MailChimp sign ups. 

Would there be any value in implementing this?

**Comment by chrisfosterelli** [comment]
Yeah we could do Google Analytics, it's simple and easy with the payoff of getting a fair amount of information. We can make this a lower priority thing.

Not sure if we can tie into MailChimp though, as their JS is fairly sandboxed within itself.
