### ISSUE TITLE
Update Board Members

### ISSUE THREAD

**Issue by cryptonym0** [trucsclub/trucsclub.github.io#86]
*Acceptance Criteria*
# All new board members appear on the board member list
# All old board members appear on the previous board members list.

**Comment by cryptonym0** [comment]
This is a 20 seconder:

<li>Elycia Buckley</li>
            <li>Mitch Hentges</li>
            <li>Kieran Haberstock</li>
            <li>Jacky Pham</li>
            <li>Lucas Rietze</li>
            <li>Thomas Winter</li>
            <li>Dyson Fraser</li>
            <li>Mwansa Kaunda</li>
            <li>Matthew Brown</li>
            <li>Marco Lussetti</li>
            <li>Tylor Pater</li>
            <li>Ardash Jain</li>
            <li>Taylar Masson</li>

and 

 <li>Chris Foster</li>
            <li>Patrick Lam</li>
            <li>Joshua Lindsay</li>
            <li>Steven Lyall</li>
            <li>Salman Almishari</li>
            <li>Maksim Avdyushkin</li>
            <li>Lee Bergstrand</li>
            <li>Chad Fawcett</li>
            <li>Jonathan Halls</li>
            <li>Bo Han</li>
            <li>Mitch Hentges</li>
            <li>Hao Jin</li>
            <li>Amarpreet Kaur</li>
            <li>Tiasa	Mondol</li>
            <li>Keenan Ratushniak</li>
            <li>Nicole Saat</li>
            <li>Stefan Schielke</li>
            <li>Paige Sutherland</li>
            <li>Brendan Watson</li>

**Comment by marcolussetti** [comment]
Mitch probably does not need to be listed in both the current and past section. I would say that it's sufficient that he be listed in the current members section.

**Comment by mitchhentges** [comment]
U forgot `Daniel Jewison`, but I gotchu
