### ISSUE TITLE
Manually style Facebook/Twitter buttons

### ISSUE THREAD

**Issue by mitchhentges** [trucsclub/trucsclub.github.io#90]
By embedding the buttons, we're allowing FB/Twitter scripts to run on our site, which is both a bit of a privacy concern, as well as a performance/layout problem: See how these things pop up when you load the page:
![out](https://cloud.githubusercontent.com/assets/7784737/20047182/917acdb0-a466-11e6-9a7a-2859f0e527da.gif)

**Comment by frogcrush** [comment]
We could also make the buttons into simple hyperlinks with images inside them. This would also allow us to easily add Instagram and Snapchat links.
